(function(g){var window=this;'use strict';var f3=function(a){a.publish("cardstatechange",a.Pl()&&a.Vp()?1:0)},g3=function(a,b){var c=g.Ra(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},sfb=function(a){var b=g.Hm(a);
a=g.Km(a);return new g.pm(b.x,b.y,a.width,a.height)},tfb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.Ms(a,b,function(){g.Ns(e);c.apply(a,arguments)},d)},j3=function(a){a=g.Ua(a);
delete h3[a];g.Mg(h3)&&i3&&i3.stop()},vfb=function(){i3||(i3=new g.op(function(){ufb()},20));
var a=i3;a.isActive()||a.start()},ufb=function(){var a=g.Ya();
g.Cg(h3,function(b){wfb(b,a)});
g.Mg(h3)||vfb()},k3=function(a,b,c,d){g.Bp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.U=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.L=0;this.D=null},wfb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.L=1E3/(b-a.D);a.D=b;xfb(a,a.progress);a.progress==1?(a.j=0,j3(a),a.onFinish(),a.Ks()):a.isPlaying()&&a.fO()},xfb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.U[c]-a.B[c])*b+a.B[c]},yfb=function(a,b){g.Uh.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.L;this.state=b.j},l3=function(a,b,c,d,e){k3.call(this,b,c,d,e);
this.element=a},zfb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
l3.call(this,a,b,c,d,e)},Afb=function(a){return Math.pow(a,3)},Bfb=function(a){return 3*a*a-2*a*a*a},Cfb=function(a){g.O.call(this);
this.B=a||window;this.j=[]},m3=function(a){return a.baseUrl||null},n3=function(a,b){return g.un(g.Kl(a,b),function(c){return!!c})},Dfb=function(a,b,c){function d(ma){var X=ma.hovercardButton;
if(!X)return null;X=X.subscribeButtonRenderer;if(!X)return null;var R=f(X.unsubscribedButtonText),Y=f(X.subscribedButtonText);if(X.subscribed){var v=f(X.subscriberCountWithUnsubscribeText);var U=f(X.subscriberCountText)}else v=f(X.subscriberCountText),U=f(X.subscriberCountWithSubscribeText);var $a=null;if(ma.signinEndpoint){$a=g3(ma,"signinEndpoint","webNavigationEndpointData","url");if(!$a){var wb,pb;$a=(pb=g.Q((wb=X.signInEndpoint)==null?void 0:wb.commandMetadata,g.Z1))==null?void 0:pb.url}if(!$a)return null}return R&&
(Y||$a)?{subscribed:X.subscribed,subscribeText:R,subscribeCount:v,unsubscribeText:Y,unsubscribeCount:U,enabled:X.enabled,signinUrl:$a,classic:ma.useClassicSubscribeButton}:null}
function e(ma){if(ma){var X=[],R=ma.videoId;R&&X.push("v="+R);(R=ma.playlistId)&&X.push("list="+R);(ma=ma.startTimeSeconds)&&X.push("t="+ma);return"/watch?"+X.join("&")}}
function f(ma){if(!ma)return null;var X=ma.simpleText;return X?X:ma.runs?g.Kl(ma.runs,function(R){return R.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,y=!1,A=null,C=null,F=null,H=null,L=null,N=null;if(h==="VIDEO")g.Q(l,g.hy)?m=g.Q(l,g.hy).url:(N=g.Q(l,g.qR),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.Q(l,g.hy)?m=g.Q(l,g.hy).url:(N=g.Q(l,g.qR),m=e(N)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(y=g3(l,"browseEndpoint","browseId"))u=y,m="/channel/"+u;n=!1;q="new";(y=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((F=g3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=g3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g3(b,"title","accessibility","accessibilityData","label");var W=b.endpoint?b.endpoint.clickTrackingParams:
null,V="";if(b.metadata){var da=f(b.metadata);da&&(V=da)}return{id:"element-"+c,type:h,title:f(b.title),metadata:V,callToAction:f(b.callToAction),MY:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,sG:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:y,targetUrl:m||null,aaa:n,sessionData:W?{itct:W}:null,Mfa:q,CE:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:n3(b.impressionUrls||[],m3),Q$:n3(b.hovercardShowUrls||[],m3),clickUrls:n3(l.loggingUrls||[],m3),visualElement:g.Sw(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:N||null}},Efb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:n3(a.impressionUrls||[],m3),elements:n3(a.elements||[],function(d,e){return Dfb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Sw(a.trackingParams));return c},Ffb=function(a){g.qY.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.U=[];this.Z=!0;this.L=0;a=a.V();this.W=g.TP(a)||g.VP(a);this.events=new g.dG(this);g.P(this,this.events);this.events.T(this.player,g.CE("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.DE("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.pc);this.events.T(window,"focus",this.Nda);this.load();var b=g.kh("STYLE");(g.bh("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.ph(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Gfb=function(a){return a.player.getVideoData().Qf?"current":a.W?"new":"current"},o3=function(a){return a.player.V().playerStyle==="creator-endscreen-editor"},Hfb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=Efb(f,Gfb(a))));p3(a,f)},
urlParams:{v:c},withCredentials:!0};a.W&&(c.urlParams.ptype="embedded");var d=b.Rw;d&&(c.postParams={ad_tracking:d});if(b=g.LMa(b))if(b=g.Rf(b),b=g.Nf(b))a.C=g.Pr(b,c)},p3=function(a,b,c){c=c===void 0?!0:c;
a.player.gf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.x(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.U.length>0&&(a.U.forEach(function(l){l.dispose()}),a.U.length=0);
a.L=0;if((a.endscreen=b)&&b.elements){c&&Ifb(a);c=[];d=new g.AE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().B||(a.B=new g.S({J:"div",S:"ytp-ce-shadow"}),g.wS(a.player,a.B.element,4),a.D=new g.Ay(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Jfb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.wS(a.player,f.element,4);var h=new g.AE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Kfb(a,f,e)}else g.dx(new g.jt("buildEndscreenElement null",
e))}a.player.Se(c);a.pc()}},Ifb=function(a){var b=g.Uw(),c=g.Vw();
c&&b&&a.endscreen.visualElement&&g.or(g.px)(void 0,c,b,a.endscreen.visualElement)},Jfb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={J:"div",Ka:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.CE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-covering-image",Y:q3(b)},{J:"div",S:"ytp-ce-covering-shadow-top"},{J:"a",S:"ytp-ce-covering-overlay",Y:{href:r3(a,b.targetUrl),tabindex:"-1"},X:[{J:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Gp(b.title||"")},ya:b.title},{J:"div",S:b.sG?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.S(a);break;case "PLAYLIST":a={J:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.CE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-covering-image",Y:q3(b)},{J:"div",S:"ytp-ce-covering-shadow-top"},{J:"a",S:"ytp-ce-covering-overlay",Y:{href:r3(a,b.targetUrl),tabindex:"-1"},X:[{J:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Gp(b.title||"")},ya:b.title},{J:"div",S:"ytp-ce-playlist-count",
X:[{J:"div",S:"ytp-ce-playlist-icon"},{J:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.S(a);break;case "CHANNEL":c={J:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.CE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-expanding-overlay",X:[{J:"div",S:"ytp-ce-expanding-overlay-hider"},{J:"div",S:"ytp-ce-expanding-overlay-background"},{J:"div",S:"ytp-ce-expanding-overlay-content",
X:[{J:"div",S:"ytp-ce-expanding-overlay-body",X:[{J:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{J:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:r3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Gp(b.title||"")},ya:b.title},b.subscribeButton?{J:"div",S:"ytp-ce-subscribe-container",X:[{J:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{J:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{J:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{J:"div",S:"ytp-ce-expanding-image",Y:q3(b)}]};c=new g.S(c);var d=g.dh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.wp(d,"ytp-ce-subscribe-button");if(a.player.V().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.VY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.U.push(e)}break;case "WEBSITE":a={J:"div",Ka:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.CE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-expanding-overlay",X:[{J:"div",S:"ytp-ce-expanding-overlay-hider"},{J:"div",S:"ytp-ce-expanding-overlay-background"},{J:"div",S:"ytp-ce-expanding-overlay-content",X:[{J:"div",S:"ytp-ce-expanding-overlay-body",X:[{J:"div",
S:"ytp-ce-expanding-overlay-body-padding",X:[{J:"div",S:"ytp-ce-website-title",Y:{dir:g.Gp(b.title||"")},ya:b.title},{J:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{J:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:r3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{J:"div",S:"ytp-ce-expanding-image",Y:q3(b)},{J:"div",S:"ytp-ce-expanding-icon",Y:Lfb(b.iconUrl)}]};c=new g.S(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={J:"div",S:"ytp-ce-merchandise-price-container",
X:[{J:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.X.push({J:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={J:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.CE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-expanding-overlay",X:[{J:"div",S:"ytp-ce-expanding-overlay-hider"},{J:"div",S:"ytp-ce-expanding-overlay-background"},{J:"div",S:"ytp-ce-expanding-overlay-content",
X:[{J:"div",S:"ytp-ce-expanding-overlay-body",X:[{J:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{J:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.Gp(b.title||"")},ya:b.title},c,{J:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{J:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:r3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{J:"div",S:"ytp-ce-expanding-image",Y:q3(b)},{J:"div",S:"ytp-ce-merchandise-invideo-cta-container",X:[{J:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.S(a)}b.isPlaceholder&&g.wp(c.element,"ytp-ce-placeholder");return c},q3=function(a){if(a.MY)var b=a.MY.thumbnails;
return Lfb(b?b[b.length-1].url:null)},Lfb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Kfb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.Z&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.L+=m;a.L>0?(g.wp(b.element,"ytp-ce-force-expand"),s3(a,c.id,!0)):(g.yp(b.element,"ytp-ce-force-expand"),g.yp(b.element,"ytp-ce-element-hover"),s3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Mfb(a,b,c)});
b.listen("mouseleave",function(){Nfb(a,b,c)});
a.player.V().B||b.listen("click",function(){g.wp(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Ofb(a,c,m)});
b.listen("keypress",function(m){Ofb(a,c,m)});
b.listen("focus",function(){Mfb(a,b,c)});
b.listen("blur",function(){Nfb(a,b,c)});
b.listen("touchstart",function(){Mfb(a,b,c)});
var l=g.eh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.yp(b.element,"ytp-ce-element-hover");g.yp(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Z=m.keyCode===9&&!m.shiftKey});
d(g.eh("ytp-sb-subscribe",b.element));d(g.eh("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Ofb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.vp(d,"ytp-ce-element");){g.vp(d,"subscribe-label")&&Pfb(a,b);
if(g.vp(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.vp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Nfb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.Mfa==="new")Pfb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Rf(r3(a,b.targetUrl)),c=g.Nf(c),g.pz(c,void 0,b.sessionData);else{var e=g.hQ(a.player.V())||a.player.getVideoData().Qf,f=function(){var h=r3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=
g.ur(h);e&&n&&(n.v||n.list)?a.player.Jp(n.v,l,n.list,!1,void 0,m||void 0):g.oz(h,l)};
Pfb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},r3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.pQ(a)+b}else return"";return b},Mfb=function(a,b,c){g.vp(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.wp(b.element,"ytp-ce-element-hover"):a.player.V().B?(new g.op(function(){g.wp(b.element,"ytp-ce-element-hover")},200)).start():g.wp(b.element,"ytp-ce-element-hover"),t3(a,c.Q$),s3(a,c.id,!0))},Nfb=function(a,b,c){g.yp(b.element,"ytp-ce-element-hover");
g.yp(b.element,"ytp-ce-force-expand");s3(a,c.id,!1)},s3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.x(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Ap(a.j[e].element,"ytp-ce-element-shadow-show",c)},t3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||o3(a))c&&c();else{b=Qfb(a,b);var e=0,f=!1,h=new g.op(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.kv(b[a],d)}},Pfb=function(a,b,c){t3(a,b.clickUrls,c);
(a=g.Vw())&&b.aaa&&g.Ax(a,b.visualElement)},Qfb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Rfb(b[d],c));return a},Rfb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Sfb=function(a){return typeof a==="string"?a:""},u3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Tfb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},v3=function(a){return a.value?a.value:null},w3=function(a){if(!a)return null;
var b=g.Rf(Sfb(a.value));b=g.Nf(b);if(!b)return null;var c=u3(a.target,Ufb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new Tfb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},Vfb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Yfb=function(a){if(!a)return null;
var b=u3(a.type,Wfb),c=u3(a.trigger,Xfb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=w3(a?a:null);return b?new Vfb(b,c,a):null},Zfb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},$fb=function(a,b){return g.Wb(a.action,b)},agb=function(a,b){this.context=a;
this.j=b},bgb=function(a){return a.customMessage?x3("div","iv-card-message",a.customMessage):""},y3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{J:"div",S:"iv-card-image",Y:{style:a},X:c}},cgb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.x(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(x3("li","",c.value));return{J:"ul",S:"iv-card-meta-info",X:b}},x3=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Gp(c);return{J:a,Y:b,ya:c}},dgb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.QE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.QE+");");c.dir=g.Gp(a.customMessage);var d=[{J:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({J:"span",S:"iv-card-link-icon"}));return{J:"div",Ka:b,Y:c,X:d}},z3=function(a,b,c,d){if(d){b=g.x(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Bj.click,5)}},egb=function(a,b){this.merchant=a;
this.price=b},fgb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},ggb=function(a,b){return b?b:fgb(a)?"current":"new"},A3=function(a,b){g.O.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Ua=new Map;this.Za=new Map;this.context.K.addEventListener(g.CE("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)});
this.context.K.addEventListener(g.DE("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},B3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.gO(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},hgb=function(a){var b;
return((b=g.Q(a,g.hy))==null?0:b.url)?g.Q(a,g.hy).url:(a=g.Q(a,g.qR))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},C3=function(a,b,c){return{l_:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
C3:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
DN:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},igb=function(a,b,c){A3.call(this,b,c);
var d=this;this.K=a;this.eventId=null;this.Bb=this.La=this.Mb=this.C=this.isInitialized=!1;this.cards=[];this.ub=this.W=this.Ma=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.U=this.Mf=this.Fa=null;this.L=0;this.Ea=new g.op(function(){},c.ea.Ak?4E3:3E3);
g.P(this,this.Ea);this.ib=new g.op(function(){});
g.P(this,this.ib);this.Ba=new agb(c,function(e,f,h,l,m,n){B3(d,e,f,h,l,m,n)});
this.Z=new g.S({J:"div",S:"iv-drawer",Y:{id:"iv-drawer"},X:[{J:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{J:"span",S:"iv-drawer-header-text"},{J:"button",Ka:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Masquer les fiches",tabindex:"0"}}]},{J:"div",S:"iv-drawer-content"}]});g.P(this,this.Z);this.D=this.Z.element;this.bb=new g.Ay(this.Z,330);g.P(this,this.bb);this.Vb=g.eh("iv-drawer-header-text",this.D);this.B=g.eh("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Mb&&D3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Mb=d.C)&&E3(d)});
this.Pa=new g.dG(this);g.P(this,this.Pa);this.K.addEventListener("videodatachange",this.Gu.bind(this))},jgb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){D3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){E3(a)});
var c=b.headerText;g.rh(a.Vb,c);a.W&&a.W.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.Sw(b.trackingParams);a.U=g.Sw(b.closeTrackingParams);a.Mf=g.Sw(b.iconTrackingParams)},kgb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.L,d=a.K.V().experiments.fb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"simple",teaserText:g.Ox(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Bj:{},Yp:null,qk:e.trackingParams?g.Sw(e.trackingParams):null,Mf:f&&f.trackingParams?g.Sw(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
QE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};F3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"simple",teaserText:g.Ox(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:G3(a,c,b,f),sponsored:!1,Bj:C3(f,e,f.command),Yp:f.trackingParams?g.Sw(f.trackingParams):null,qk:e.trackingParams?g.Sw(e.trackingParams):null,Mf:l&&l.trackingParams?g.Sw(l.trackingParams):null,imageUrl:H3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.Ox(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,QE:null,title:f.title?g.Ox(f.title):"",customMessage:f.callToAction?g.Ox(f.callToAction):"",url:g.Q(f.command,g.hy).url?w3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.hy).url}):null,onClickCommand:null};F3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"collaborator",teaserText:g.Ox(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:G3(a,c,b,e),sponsored:!1,Bj:C3(e,f,e.endpoint),Yp:e.trackingParams?g.Sw(e.trackingParams):null,qk:f.trackingParams?g.Sw(f.trackingParams):null,Mf:l&&l.trackingParams?g.Sw(l.trackingParams):null,channelId:g.Q(e.endpoint,g.FR).browseId,customMessage:e.customText?g.Ox(e.customText):null,profileImageUrl:H3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.Ox(e.channelName):"",metaInfo:[e.subscriberCountText?g.Ox(e.subscriberCountText):""],url:w3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.FR).canonicalBaseUrl?g.Q(e.endpoint,g.FR).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.FR).browseId}),onClickCommand:null};F3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"playlist",teaserText:g.Ox(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:G3(a,c,b,e),sponsored:!1,Bj:C3(e,f,e.action),Yp:e.trackingParams?g.Sw(e.trackingParams):null,qk:f.trackingParams?g.Sw(f.trackingParams):null,Mf:l&&l.trackingParams?g.Sw(l.trackingParams):null,CI:H3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.Ox(e.customMessage):null,playlistVideoCount:g.Ox(e.playlistVideoCount),title:e.playlistTitle?g.Ox(e.playlistTitle):"",metaInfo:[e.channelName?g.Ox(e.channelName):
"",e.videoCountText?g.Ox(e.videoCountText):""],url:w3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:hgb(e.action)}),onClickCommand:null};F3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"video",teaserText:g.Ox(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:G3(a,c,b,e),sponsored:!1,Bj:C3(e,f,e.action),Yp:e.trackingParams?g.Sw(e.trackingParams):null,qk:f.trackingParams?g.Sw(f.trackingParams):null,Mf:l&&l.trackingParams?g.Sw(l.trackingParams):null,CI:H3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.Ox(e.lengthString):null,customMessage:e.customMessage?g.Ox(e.customMessage):null,title:e.videoTitle?g.Ox(e.videoTitle):"",metaInfo:[e.channelName?g.Ox(e.channelName):
"",e.viewCountText?g.Ox(e.viewCountText):""],isLiveNow:!!e.badge,url:w3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:hgb(e.action)}),onClickCommand:null};F3(a,b)}}}}}a.L++},H3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},G3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},mgb=function(a,b){if(b=lgb(a,b))b===a.j&&(a.j=null),a.K.removeCueRange(b.Hf.id),g.ph(b.tP),g.$b(a.cards,b),a.HJ(),I3(a)},D3=function(a,b,c){if(!a.C){a.bb.show();
a.Va=new g.op(function(){g.wp(a.context.K.getRootNode(),g.hM.IV_DRAWER_OPEN)},0);
a.Va.start();a.Pa.T(a.B,"mousewheel",function(h){a.Ea.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.Vw();d&&a.Fa&&a.U&&g.yx(d,[a.Fa,a.U]);b={TRIGGER_TYPE:b};for(var e=g.x(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.m0||(f.m0=!0,ngb(a.context.logger,f.Hf.Bj.l_,b)),d&&g.yx(d,[f.Hf.Yp]);f3(a.K);c&&(a.G=new g.op(function(){a.Ma=a.W;a.ub.focus()},330),a.G.start())}},E3=function(a){a.C&&(a.bb.hide(),g.Ts(a.Pa),g.yp(a.context.K.getRootNode(),g.hM.IV_DRAWER_OPEN),a.C=!1,f3(a.K),a.G&&a.G.stop(),a.G=new g.op(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.G.start())},ogb=function(a){g.xp(a.Jb(),
[g.hM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.wS(a.K,a.D,5);a.uJ();a.W=g.eh("ytp-cards-button",a.K.getRootNode());a.ub=g.eh("iv-drawer-close-button",a.D);a.isInitialized=!0},pgb=function(a){a.qa.push(g.Dv("iv-teaser-shown",a.n5,a));
a.qa.push(g.Dv("iv-teaser-hidden",a.Faa,a));a.qa.push(g.Dv("iv-teaser-clicked",a.m5,a));a.Bb=!0},qgb=function(a,b){var c;
return b.onClickCommand&&((c=g.Q(b.onClickCommand,g.bdb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.ra=b,!0):!1},rgb=function(a,b){a.ra=b;
var c=a.K.getVideoData();if(!c)return!1;c=g.LQ(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.Q(h[0],g.O4a))==null?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},F3=function(a,b){if(!qgb(a,b)||rgb(a,b)){var c=sgb(a,b);
if(c){var d={Hf:b,tP:c.element,m0:!1};if(b.onClickCommand)a.K.N("web_infocards_teaser_show_logging_fix")&&(a.Bb||pgb(a),mgb(a,b.id),c=a.findLastIndex(d),g.fc(a.cards,c,0,d));else{a.isInitialized||ogb(a);mgb(a,b.id);var e=a.findLastIndex(d);g.fc(a.cards,e,0,d);c.Ga(a.B,e);a.HJ()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,I3(a),tgb(a,d),D3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.K.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&ugb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){ugb(a,d)}),I3(a))}}},sgb=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{J:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=dgb(b);c={J:"div",Ka:["iv-card"],X:[{J:"a",S:"iv-click-target",Y:{href:b.url?v3(b.url)||"":""},X:[y3(b.imageUrl,c),{J:"div",S:"iv-card-content",X:[x3("h2",void 0,b.title),d]}]}]};c=new g.S(c);z3(a,g.ch("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={J:"div",Ka:["iv-card","iv-card-channel"],X:[{J:"a",Ka:["iv-click-target"],Y:{href:v3(b.url)||"","data-ytid":b.channelId},X:[y3(b.profileImageUrl),
{J:"div",S:"iv-card-content",X:[bgb(b),{J:"h2",S:"iv-card-primary-link",ya:b.title},cgb(b)]}]}]};c=new g.S(c);z3(a,g.ch("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={J:"div",Ka:["iv-card","iv-card-playlist"],X:[{J:"a",S:"iv-click-target",Y:{href:v3(b.url)||""},X:[y3(b.CI,{J:"div",S:"iv-card-image-overlay",X:[{J:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{J:"div",S:"iv-card-content",X:[bgb(b),x3("h2","iv-card-primary-link",b.title),cgb(b)]}]}]};
c=new g.S(c);z3(a,g.ch("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=b.offers.length!=0;c=["iv-card"];d="";var f=dgb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({J:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({J:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={J:"div",X:e});e=b.url?v3(b.url)||"":"";c={J:"div",Ka:c,Y:{tabindex:"0"},X:[{J:"a",Ka:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{J:"div",S:"iv-card-content",X:[b.sponsored?{J:"div",S:"iv-card-sponsored",X:["Lien commercial",{J:"div",S:"iv-ad-info-container",X:[{J:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{J:"div",S:"iv-ad-info-icon-container",X:[{J:"div",S:"iv-ad-info-icon"},{J:"div",S:"iv-ad-info-callout"}]}]}]}:"",{J:"a",S:"iv-click-target",Y:{href:e},X:[x3("h2",d,b.title),f]}]}]};c=new g.S(c);d=g.kh("span");g.rh(d,"Vous voyez ce produit, car nous pensons qu'il est pertinent pour la vid\u00e9o. Il se peut que le marchand r\u00e9mun\u00e8re Google.");
c.Gd(d,"adInfo");z3(a,g.ch("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{J:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{J:"span",Ka:["yt-badge","yt-badge-live"],ya:"EN DIRECT MAINTENANT"}:null;e={J:"div",Ka:["iv-card","iv-card-video"],X:[{J:"a",S:"iv-click-target",Y:{href:((c=b.url)==null?void 0:v3(c))||""},X:[y3(b.CI,d),{J:"div",S:"iv-card-content",X:[bgb(b),x3("h2","iv-card-primary-link",b.title),cgb(b),f]}]}]};c=new g.S(e);
z3(a,g.ch("iv-click-target",c.element),b,b.url);b=c;break;default:return null}return b},vgb=function(a){if(a.j)return a.j.Hf.type==="productListing";
if(a.K.N("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.Ll(a.cards,function(c){return c.Hf.type==="productListing"})}return g.Ll(a.cards,function(c){return c.Hf.type==="productListing"})},I3=function(a){g.Ap(a.K.getRootNode(),"ytp-cards-shopping-active",vgb(a))},ugb=function(a,b){if(!g.vp(a.K.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Vw(),d=a.j?a.j.Hf.Mf:a.Mf;
c&&d&&g.zx(c,[d]);a.j=b;I3(a)}(c=a.isInitialized&&a.Jb().style.display=="none")||(c=a.context.K.getPlayerState(),d=c===0&&a.context.K.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Hf.teaserDurationMs&&a.K.JC(!0,{teaserText:b.Hf.teaserText,durationMs:b.Hf.teaserDurationMs,onClickCommand:b.Hf.onClickCommand});a.ib.isActive()||((!a.C||!a.Ea.isActive()&&a.La)&&tgb(a,b),a.ib.start(910+b.Hf.teaserDurationMs))}},tgb=function(a,b){a.Z.Fb?(b=new k3([0,
a.B.scrollTop],[0,b.tP.offsetTop],600,Bfb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.Kx(a.Z,!0),a.B.scrollTop=b.tP.offsetTop,g.Kx(a.Z,!1))},J3=function(a){return a.j&&a.j.Hf?a.j.Hf:a.cards[0]&&a.cards[0].Hf?a.cards[0].Hf:null},lgb=function(a,b){return g.Wb(a.cards,function(c){return c.Hf.id===b})},K3=function(a,b,c){A3.call(this,a,b);
this.annotation=c;this.isActive=!1},wgb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(Number(b.start_ms),Number(b.end_ms),a.annotation.id,function(){a.show()},function(){a.hide()})},L3=function(a,b,c){K3.call(this,a,b,c);
this.B=null;this.U=!1;this.C=null;this.D=!1;this.j=this.L=this.G=null},xgb=function(a,b){var c=c===void 0?0:c;
var d=sfb(b).width;g.Fm(b,d);c=new zfb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Afb);g.P(a,c);a.context.C.listen(c,"begin",function(){g.Lm(b,!0)});
c.play()},Agb=function(a,b){if(b.channel_name){var c=a.createElement({J:"div",
Ka:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({J:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.VY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.K,!1),a.j.Ga(d));var f=a.createElement({J:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({J:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Lm(h,!1);var l=a.createElement({J:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.zm(l,"right",b.image_width+"px");g.mh(a.Jb(),l);a.C=new g.op(function(){ygb(a,h,l)},500);
g.P(a,a.C);a.context.j.listen(a.Jb(),"mouseover",function(){zgb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Jb(),"mouseout",function(){a.C.start()})}},zgb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Km(b);a.j||(b.style.width=g.Em(f.width,!0),c.style.width=g.Em(f.width,!0));g.zm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.zm(d,"right","1px");a.D=!0;g.Lm(b,!0);a.G=new g.op(function(){g.wp(this.Jb(),"iv-branding-active")},0,a);
a.G.start()}},ygb=function(a,b,c){g.yp(a.Jb(),"iv-branding-active");
a.L=new g.op(function(){g.Lm(b,!1);a.j||(c.style.width=g.Em(0,!0))},250);
a.L.start();a.D=!1},Bgb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.ea=c;this.videoData=d;this.logger=e;this.K=f;this.B=h},Cgb=function(a,b,c){K3.call(this,a,b,c);
var d=this;this.W=this.isCollapsed=this.Z=!1;this.L=5E3;this.B=this.C=this.j=this.D=null;this.U=this.createElement({J:"div",Ka:["iv-promo-contents"]});this.G=new g.op(function(){d.j.setAttribute("aria-hidden","true");g.Lm(d.C,!1);g.Lm(d.B,!0)},700,this);
g.P(this,this.G)},Fgb=function(a,b,c){c.stopPropagation();
Dgb(a);Egb(a,b);a.j.focus()},Ggb=function(a){a.isCollapsed||a.W||a.D||(g.wp(a.Jb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Dgb=function(a){a.G.stop();
a.isCollapsed&&(g.zp(a.Jb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Lm(a.B,!1),g.Lm(a.C,!0))},Egb=function(a,b){a.D||(a.D=g.Ii(function(){Hgb(this);
Ggb(this)},b,a))},Hgb=function(a){a.D&&(g.Ma.clearTimeout(a.D),a.D=null)},Igb=function(a){this.K=a},ngb=function(a,b,c){b&&(c?M3(a,b.map(function(d){return g.Mo(d,c)})):M3(a,b))},M3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.x(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.kv(m,f);d&&(e++,d!==0&&a.K.sendVideoStatsEngageEvent(d,f))},Jgb=function(a){g.qY.call(this,a);
var b=this;this.qa=this.W=!1;this.loadNumber=0;this.L={};this.logger=new Igb(this.player);this.D=new g.dG(this);this.G=this.U=null;this.events=new g.dG(this);this.uh=this.Z=this.j=null;this.ra=[];g.P(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.o5,this);this.subscribe("resize",this.sM,this);this.player.V().La.subscribe("vast_info_card_add",this.G1,this);g.P(this,this.events);this.Ba=this.createElement({J:"div",S:"video-custom-annotations"});this.B=new g.S({J:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.B);g.wS(this.player,this.B.element,4);this.B.hide();this.C=new g.S({J:"div",Ka:["ytp-iv-video-content"]});g.P(this,this.C);a=this.createElement({J:"div",S:"video-annotations"});
a.appendChild(this.Ba);this.C.element.appendChild(a);this.Rv()&&this.load();var c=this.createElement({J:"style"});(g.bh("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.ph(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Kgb=function(a){a=a.createElement({J:"div",
Ka:["annotation","annotation-type-custom"]});g.Lm(a,!1);return a},Lgb=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.Kx(a.B,b);g.Kx(a.C,b)},Mgb=function(a,b,c){a.W=!0;
a.G=g.Pr(b,c)},Ngb=function(a,b){for(var c={},d=g.x(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Sa(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Ngb(a,e))}return c},Rgb=function(a){var b=a.player.getVideoData();
if(b.Ua){var c=a.player.V().La.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.Er(h)&&h.responseXML?h.responseXML:null)&&Ogb(a,h)}};
g.rt()&&(d.onFinish=Pgb(a,d.onFinish));d.postParams={ic_only:"1"};Qgb(d,c);a.W=!0;g.Pr(b.Ua,d)}}},Qgb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.MJ&&(a.postParams.ic_coll=b.MJ);b.uP&&(a.postParams.ic_xml=b.uP);b.JN&&(a.postParams.ic_track=b.JN)},Sgb=function(a){var b=new g.S({J:"div"});
g.Lm(b.element,!1);var c=new igb(a.player,b.element,N3(a));g.P(c,b);b.Ga(a.B.element);c.kI();return c},Ugb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.qa=!0,Tgb(a,b),b.headerText&&a.uh&&(c=g.Ox(b.headerText),a.uh.setAttribute("title",c))},N3=function(a){if(!a.Z){var b=new Cfb(a);
g.P(a,b);var c=new g.Jk(a);g.P(a,c);a.Z=new Bgb(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.ek)}return a.Z},Ogb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.Vw();if(e){var f=g.Uw();f&&g.or(g.ox)(void 0,e,f,[g.Sw(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Ngb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=u3(f.type,Vgb),p=u3(f.style,Wgb),q=Sfb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=Yfb;if(t==null)var u=null;else if(g.Ra(t)){l=[];for(var y=g.x(t),A=y.next();!A.done;A=y.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var F=f(t);u=F?[F]:[]}e=m&&n?new Zfb(m,n,p,u,r):null}else e=null}catch(da){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=Kgb(f),L=null;switch(l.type){case "branding":if(f.player.V().Md)break;f.B.element.appendChild(H);L=new L3(H,N3(f),l);break;case "promotion":g.wS(f.player,H,4),L=new Cgb(H,N3(f),l)}L&&L.kI();if(f=L)g.P(a,f),a.L[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=Sgb(a),g.P(a,a.j));if(e.type==="card"){H=a.j;var N=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(N)switch(f=e.tracking||{},f={l_:f.impression,click:f.click,close:f.close,C3:f.teaser_impression,DN:f.teaser_click},l=e.tracking_params||{},L=null,N){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Bj:f,Yp:l.card?g.Sw(l.card):null,qk:l.teaser?g.Sw(l.teaser):null,Mf:l.icon?g.Sw(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:w3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};F3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Bj:f,
Yp:l.card?g.Sw(l.card):null,qk:l.teaser?g.Sw(l.teaser):null,Mf:l.icon?g.Sw(l.icon):null,CI:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:w3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};F3(H,c);break;case "productListing":e.signin_url&&(L=w3({target:"current",value:e.signin_url}));N=[];for(var W=e.offers||[],V=0;V<W.length;V++)N.push(new egb(g.kg(W[V].merchant),
g.kg(W[V].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Bj:f,Yp:l.card?g.Sw(l.card):null,qk:l.teaser?g.Sw(l.teaser):null,Mf:l.icon?g.Sw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,QE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:w3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),ara:L,Zqa:e.signin_title?e.signin_title:void 0,Yqa:e.signin_message?e.signin_message:void 0,offers:N,onClickCommand:null};F3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Bj:f,Yp:l.card?g.Sw(l.card):
null,qk:l.teaser?g.Sw(l.teaser):null,Mf:l.icon?g.Sw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,QE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:w3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};F3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Bj:f,Yp:l.card?g.Sw(l.card):null,qk:l.teaser?g.Sw(l.teaser):null,Mf:l.icon?g.Sw(l.icon):null,CI:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:w3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},F3(H,c)}}else jgb(a.j,e);c=!0}}c&&
(f3(a.player),a.sM())},Tgb=function(a,b){var c=!1;
a.j||(a.j=Sgb(a),g.P(a,a.j));for(var d=g.x(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(kgb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.MR(f)||(c=a.j,d=b.headerText?g.Ox(b.headerText):"",g.rh(c.Vb,d),c.W&&c.W.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.Sw(b.trackingParams):null,c.U=b.closeButton.infoCardIconRenderer.trackingParams?g.Sw(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Mf=b.icon.infoCardIconRenderer.trackingParams?g.Sw(b.icon.infoCardIconRenderer.trackingParams):null,a.sM());f3(a.player)}},Xgb=function(a,b,c,d,e){if(!a.player.V().Md){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.FR)&&g.Q(b.navigationEndpoint,g.FR).browseId&&f.push(new Vfb("openUrl","click",new Tfb("/channel/"+g.Q(b.navigationEndpoint,g.FR).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.GR)){d.channel_id=g.Q(b.subscribeButton,g.GR).channelId;var l;b=g.Q(b.subscribeButton,g.GR);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Ox(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Ox(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Ox(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Ox(b.subscriberCountWithSubscribeText)));var m,n=((m=g.Q((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.Z1))==null?void 0:m.url)||"";l={subscribeText:g.Ox(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.Ox(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Zfb(c,"branding","branding",f,d);l=Kgb(a);a.B.element.appendChild(l);f=new L3(l,N3(a),f);f.kI();g.P(f,f);a.L[c]=f}},Pgb=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.Ja()||a.ra.push(g.hp.dj(function(){b.apply(null,g.z(c))}))}},Ygb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.pS.prototype.JC=g.ca(35,function(a,b){var c=g.DY(this.Db());c&&c.JC(a,b)});
var h3={},i3=null;g.Za(k3,g.Bp);g.k=k3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;j3(this);this.startTime=a=g.Ya();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.hM();this.Do("play");this.isPaused()&&this.Do("resume");this.j=1;var b=g.Ua(this);b in h3||(h3[b]=this);vfb();wfb(this,a);return!0};
g.k.stop=function(a){j3(this);this.j=0;a&&(this.progress=1);xfb(this,this.progress);this.onStop();this.Ks()};
g.k.pause=function(){this.isPlaying()&&(j3(this),this.j=-1,this.Do("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.Do("destroy");k3.Zf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.fO=function(){this.Do("animate")};
g.k.Do=function(a){this.dispatchEvent(new yfb(a,this))};
g.Za(yfb,g.Uh);g.Za(l3,k3);l3.prototype.C=function(){};
l3.prototype.fO=function(){this.C();l3.Zf.fO.call(this)};
l3.prototype.Ks=function(){this.C();l3.Zf.Ks.call(this)};
l3.prototype.hM=function(){this.C();l3.Zf.hM.call(this)};
g.Za(zfb,l3);zfb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Cfb,g.O);g.k=Cfb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Va)(c,d||this.B);a=g.Ms(a,b,c);this.j.push(a);return a};
g.k.IG=function(a,b,c,d){c=(0,g.Va)(c,d||this.B);a=tfb(a,b,c);this.j.push(a);return a};
g.k.Oc=function(a){g.Ns(a);g.$b(this.j,a)};
g.k.removeAll=function(){g.Ns(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.O.prototype.xa.call(this)};g.w(Ffb,g.qY);g.k=Ffb.prototype;g.k.load=function(){g.qY.prototype.load.call(this);if(!o3(this)){var a=g.MMa(this.player.getVideoData());a?(a=Efb(a,Gfb(this)),p3(this,a,!1)):Hfb(this)}};
g.k.unload=function(){p3(this,null);this.C&&(this.C.abort(),this.C=null);g.qY.prototype.unload.call(this)};
g.k.ri=function(a,b){return o3(this)?a==="loadCustomEndscreenRenderer"?(a=Efb(b,"new"),p3(this,a),!0):null:null};
g.k.getOptions=function(){return o3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.pc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Zgb.length;f++){var h=Math.abs(b.width-Zgb[f]);if(e===-1||d>=h)e=f,d=h}d=$gb[e];this.B&&g.zm(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Jm(e.element,m,f);g.Fm(e.element,n,p);g.zp(e.element,ahb);m>256||f>256?g.wp(e.element,"ytp-ce-large-round"):m>96||f>96?g.wp(e.element,"ytp-ce-medium-round"):g.wp(e.element,"ytp-ce-small-round");g.zp(e.element,bhb);m=h.left+h.width/2;h=h.top+l/2;g.wp(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.zp(e.element,$gb);g.wp(e.element,d);(e=g.dh(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")t3(this,this.endscreen.impressionUrls),(a=g.Vw())&&this.endscreen.visualElement&&g.xx(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.wp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.wp(b,"ytp-ce-shown");t3(this,c.impressionUrls);(b=g.Vw())&&g.xx(b,c.visualElement);this.player.V().U&&this.player.gb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.yp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.yp(b,"ytp-ce-shown");this.player.V().U&&this.player.gb("endscreenelementhidden",a)}};
g.k.Nda=function(a){var b=this;a.target===window&&(new g.op(function(){for(var c=g.x(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.zp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Zgb=[346,426,470,506,570,640,853,1280,1920],$gb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),bhb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],ahb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Ufb={jia:"current",Oka:"new"};var Wfb={CLOSE:"close",Tka:"openUrl",SUBSCRIBE:"subscribe"},Xfb={Rha:"click",CLOSE:"close",lja:"hidden",Lla:"rollOut",Mla:"rollOver",Wla:"shown"};Zfb.prototype.ye=function(){var a=$fb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var Wgb={cha:"anchored",P4:"branding",CHANNEL:"channel",iia:"cta",oja:"highlightText",bka:"label",PLAYLIST:"playlist",POPUP:"popup",ema:"speech",SUBSCRIBE:"subscribe",qma:"title",VIDEO:"video",Zma:"website"},Vgb={P4:"branding",Fha:"card",wia:"drawer",nja:"highlight",tka:"marker",sla:"promotion",TEXT:"text",Cna:"widget"};g.w(A3,g.O);g.k=A3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.AE(a,b,{id:c,namespace:"annotations_module"});d&&this.Ua.set(a,d);e&&this.Za.set(a,e);this.context.K.Se([a],1)};
g.k.kI=function(){this.context.B.subscribe("resize",this.HJ,this)};
g.k.Jb=function(){return this.element};
g.k.gO=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ph(this.Jb())};
g.k.HJ=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=v3(a);if(f){var h=ggb(f,a.target),l=function(){a.j&&e.context.K.pauseVideo();var m=e.context.videoData.Qf||!1,n=g.ur(f||"");m&&n&&(n.v||n.list)?e.context.K.Jp(n.v,b,n.list,!1):g.pz(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);M3(this.context.logger,c,l,d);fgb(f)||(c=g.Vw(),d=b.itct,c&&d&&g.Ax(c,g.Sw(d)))}};
g.k.xa=function(){this.Ua.clear();this.Za.clear();g.O.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.w(igb,A3);g.k=igb.prototype;g.k.Gu=function(){this.ra&&F3(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.K.getRootNode())?(a=g.Km(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.HJ=function(){var a=this.isAvailable();g.Lm(this.Jb(),a);g.Ap(this.context.K.getRootNode(),g.hM.IV_DRAWER_ENABLED,a);f3(this.K)};
g.k.destroy=function(){this.K.JC(!1);try{this.K.getRootNode().removeChild(this.D)}catch(a){}g.Ev(this.qa);g.Ts(this.Pa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();A3.prototype.destroy.call(this)};
g.k.uJ=function(){var a=this;this.context.j.listen(g.eh("iv-drawer-close-button",this.D),"click",this.t8,this);this.context.j.listen(this.B,"touchend",function(){a.Ea.start()});
this.context.j.listen(this.B,"scroll",this.T8,this);this.context.B.subscribe("onHideControls",function(){a.La=!0});
this.context.B.subscribe("onShowControls",function(){a.La=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.La=g.vp(a.K.getRootNode(),"ytp-autohide")});
this.qa.push(g.Dv("iv-button-shown",this.Eaa,this));this.qa.push(g.Dv("iv-button-hidden",this.Daa,this));pgb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Xb(this.cards,function(c){return a.Hf.startMs>c.Hf.startMs||a.Hf.startMs===c.Hf.startMs&&a.Hf.timestamp>=c.Hf.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.t8=function(){if(this.C){M3(this.context.logger,J3(this).Bj.close);var a=g.Vw();a&&this.U&&g.Ax(a,this.U);E3(this)}};
g.k.T8=function(){g.Ap(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.Eaa=function(){var a=g.Vw(),b=J3(this);b=b?b.Mf:this.Mf;a&&b&&g.yx(a,[b])};
g.k.Daa=function(){var a=g.Vw(),b=J3(this);b=b?b.Mf:this.Mf;a&&b&&g.zx(a,[b])};
g.k.n5=function(){var a=J3(this);M3(this.context.logger,a.Bj.C3);var b=g.Vw();if(b&&a)if(this.K.N("web_infocards_teaser_show_logging_fix")){var c=[];a.qk&&c.push(a.qk);a.Mf&&c.push(a.Mf);c.length>0&&g.yx(b,c)}else g.yx(b,[a.qk,a.Mf])};
g.k.Faa=function(){var a=g.Vw(),b=J3(this);a&&b&&g.zx(a,[b.qk])};
g.k.m5=function(a){var b=J3(this),c=g.Vw();this.j?a?(a=this.context.logger,M3(a,b.Bj.DN),a.K.sendVideoStatsEngageEvent(4,void 0),c&&b.qk&&g.Ax(c,b.qk)):(a=this.context.logger,M3(a,b.Bj.DN),a.K.sendVideoStatsEngageEvent(4,void 0),c&&b.Mf&&g.Ax(c,b.Mf)):(a=this.context.logger,M3(a,b.Bj.DN),a.K.sendVideoStatsEngageEvent(4,void 0),c&&this.Mf&&g.Ax(c,this.Mf))};g.w(K3,A3);K3.prototype.kI=function(){A3.prototype.kI.call(this);wgb(this)};
K3.prototype.show=function(){A3.prototype.show.call(this);var a=g.Vw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.yx(a,[g.Sw(b.itct)])};
K3.prototype.hide=function(){A3.prototype.hide.call(this);var a=g.Vw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.zx(a,[g.Sw(b.itct)])};g.w(L3,K3);
L3.prototype.wC=function(){g.wp(this.Jb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({J:"img",Ka:["branding-img","iv-click-target"],Y:{"aria-label":"Filigrane de cha\u00eene",src:a.image_url,width:a.image_width,height:a.image_height}});g.Lm(this.B,!1);var b=this.createElement({J:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Jb().appendChild(b);var c=this.annotation.ye();c&&B3(this,b,c,this.annotation.id,a.session_data);this.context.K.N("disable_branding_context")||Agb(this,
a)};
L3.prototype.show=function(){if(!this.isActive&&(K3.prototype.show.call(this),this.U||(this.wC(),this.U=!0),g.Lm(this.Jb(),!0),this.isActive=!0,this.B)){try{xgb(this,this.B)}catch(a){}g.wp(this.context.K.getRootNode(),"ytp-branding-shown");this.context.K.getRootNode().style.setProperty("--branding-image-width",this.B.getAttribute("width")+"px")}};
L3.prototype.hide=function(){this.isActive&&(K3.prototype.hide.call(this),g.Lm(this.Jb(),!1),this.isActive=!1,g.yp(this.context.K.getRootNode(),"ytp-branding-shown"))};
L3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);g.yp(this.context.K.getRootNode(),"ytp-branding-shown");K3.prototype.destroy.call(this)};g.w(Cgb,K3);g.k=Cgb.prototype;
g.k.wC=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.L=b.collapsedelay_ms||this.L;var d=["iv-promo","iv-promo-inactive"];this.Jb().setAttribute("aria-hidden","true");this.Jb().setAttribute("aria-label","Promotion");this.Jb().tabIndex=0;var e=this.annotation.ye(),f=b.image_url;if(f){var h=this.createElement({J:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({J:"img",
Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({J:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({J:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&B3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({J:"a",S:"iv-promo-txt"}),g.Tf(f,v3(e)),this.j=f):this.j=this.createElement({J:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({J:"p",X:[{J:"strong",ya:b.text_line_1}]});var m=this.createElement({J:"p",X:[{J:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({J:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({J:"button",Ka:["iv-button","iv-promo-button"],X:[{J:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({J:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&B3(this,
this.Jb(),e,this.annotation.id,b.session_data,void 0,c)}g.wp(this.j,"iv-click-target");e&&B3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({J:"p",X:[{J:"span",ya:b.text_line_1}]}),m=this.createElement({J:"p",X:[{J:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({J:"span",Ka:["yt-badge","iv-promo-badge-live"],ya:"EN DIRECT MAINTENANT"})),g.wp(this.j,"iv-click-target"),e&&B3(this,this.j,e,this.annotation.id,b.session_data,
void 0,c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.U.appendChild(this.j);p&&this.U.appendChild(p);c=this.createElement({J:"div",S:"iv-promo-actions"});this.B=this.createElement({J:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Agrandir";this.context.j.listen(this.B,"click",function(q){Fgb(a,5E3,q)});
c.appendChild(this.B);g.Lm(this.B,!1);this.context.j.listen(this.Jb(),"mouseover",this.u$,this);this.context.j.listen(this.Jb(),"mouseout",this.t$,this);this.context.j.listen(this.Jb(),"touchend",function(q){Fgb(a,5E3,q)});
this.C=this.createElement({J:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Fermer";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.p$:this.o$,this);c.appendChild(this.C);g.xp(this.Jb(),d);h&&(g.mh(this.Jb(),h),n&&h.appendChild(n));g.mh(this.Jb(),this.U);g.mh(this.Jb(),c)};
g.k.show=function(){this.isActive||(K3.prototype.show.call(this),this.Z||(this.wC(),this.Z=!0),g.Lm(this.Jb(),!0),g.Ii(function(){g.yp(this.Jb(),"iv-promo-inactive")},100,this),this.Jb().removeAttribute("aria-hidden"),this.isActive=!0,Hgb(this),Dgb(this),Egb(this,this.L))};
g.k.hide=function(){this.isActive&&(g.wp(this.Jb(),"iv-promo-inactive"),this.isActive=!1,this.Jb().setAttribute("aria-hidden","true"))};
g.k.gO=function(a,b,c,d,e,f){return this.isCollapsed?!1:K3.prototype.gO.call(this,a,b,c,d,e,f)};
g.k.u$=function(a){this.W=!0;Fgb(this,500,a)};
g.k.t$=function(){this.W=!1;Ggb(this)};
g.k.o$=function(a){a.stopPropagation();this.hide()};
g.k.p$=function(a){a.stopPropagation();Hgb(this);this.isCollapsed=!0;g.wp(this.Jb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();K3.prototype.destroy.call(this)};g.w(Jgb,g.qY);g.k=Jgb.prototype;g.k.ri=function(a,b){if(!Ygb(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.C1(b))&&Ogb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(mgb(this.j,b),f3(this.player)),!0}return null};
g.k.getOptions=function(){return Ygb(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Rv=function(){var a=this.player.V(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.WR(b)||this.player.isMutedByEmbedsMutedAutoplay()?!1:c===1&&!b.FV||a.La.get(b.videoId)||g.NR(b)||g.NMa(b)?!0:!1};
g.k.sM=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.Jm(this.C.element,a.width,a.height);g.Fm(this.C.element,a.left,a.top)}if(this.j){var b=this.player.hn();a=this.j;b=b.width;g.Ap(a.D,"iv-drawer-small",b<=426);g.Ap(a.D,"iv-drawer-big",b>=1280)}};
g.k.o5=function(a){Lgb(this,a.state);g.T(a.state,2)&&(this.Pl()&&this.Vp()&&this.player.getPresentingPlayerType()!==2&&this.KC(!1),this.JC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Er(h)&&h.responseXML?h.responseXML:null)&&(Ogb(b,h),g.wp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.qY.prototype.load.call(this);Lgb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.rt()&&(a=Pgb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().La.get(d);f&&Qgb(e,f);f=f&&(f.uP||f.MJ);if(!c.Gw||f)c.Ua?Mgb(this,c.Ua,e):(this.U=function(){if(!b.W)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.MR(h))&&!b.qa&&Ugb(b,h)},this.player.addEventListener("videodatachange",this.U));
g.wS(this.player,this.C.element,4);this.sM();(f=g.NR(c))&&Tgb(this,f);(f=g.NMa(c))&&f.featuredChannel&&Xgb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.uh=g.eh("ytp-cards-button",this.player.getRootNode());g.MR(c)&&Ugb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ua&&Mgb(this,b.Ua,a)};
g.k.unload=function(){this.player.gf("annotations_module");for(var a=g.x(Object.keys(this.L)),b=a.next();!b.done;b=a.next())this.L[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,f3(this.player));this.W=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.L={};this.B.hide();g.qY.prototype.unload.call(this);this.C.detach();this.U&&(this.player.removeEventListener("videodatachange",this.U),this.U=null)};
g.k.G1=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Rgb(this):this.load())};
g.k.Pl=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.qa};
g.k.Vp=function(){return!!this.j&&this.j.C};
g.k.KC=function(a,b,c){b=b===void 0?!1:b;this.Pl();this.j&&(a?c?D3(this.j,c,b):D3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):E3(this.j))};
g.k.JC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.V().La.unsubscribe("vast_info_card_add",this.G1,this);g.yp(this.player.getRootNode(),g.hM.IV_DRAWER_OPEN);for(var a=this.ra,b=g.hp,c=0,d=a.length;c<d;c++)b.Gk(a[c]);this.ra.length=0;g.qY.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.pY("annotations_module",Jgb);g.pY("creatorendscreen",Ffb);})(_yt_player);
